(load "conf/env")
(load "conf/mac")
(load "conf/disabled")
(load "conf/conf")
(load "conf/elpa")
(load "conf/scratch")
(load "conf/ido")
(load "conf/fonts")
(load "conf/defuns")
(load "conf/template")
(load "conf/go-setup")
(load "conf/go-mode-load")
(load "conf/go-mode")
;;(load "conf/bookmark")
(load "conf/grep")
;;(load "conf/session")
;(load "conf/el-get")

;(load "conf/cucumber")
;(load "conf/ri-emacs")
;(load "conf/rubyonrails")
;(load "conf/cc")
;(load "conf/objc")
;(load "conf/auto-complete")
;(load "conf/snippets")
;(load "conf/cua")
;;always have bug so move to last
;(load "conf/desktop")
;(load "conf/server-mode")
;;; have bug can't fix it 
;;;(load "conf/tabs")
