(load "conf/env")
(load "conf/disabled")
(load "conf/ido")
(load "conf/mac")
(load "conf/bindings")
(load "conf/scratch")
(load "conf/defuns")
(load "conf/el-get")
(load "conf/fonts")
(load "conf/template")
(load "conf/bookmark")
(load "conf/conf")
(load "conf/cucumber")
(load "conf/ri-emacs")
(load "conf/ruby-mode") 
(load "conf/rubyonrails")
(load "conf/cc")
(load "conf/objc")
(load "conf/auto-complete")
(load "conf/snippets")
(load "conf/cua")
;always have bug so move to last
(load "conf/desktop")
(load "conf/server-mode")
;; have bug can't fix it 
;;(load "conf/session")			
;;(load "conf/tabs")
