;; 设置中文字体
;;  (set-default-font "Microsoft Yahei-10")
;;(set-frame-font "Monaco-13")
;; (set-fontset-font (frame-parameter nil 'font) 'han '("Microsoft Yahei" . "unicode-bmp"))
;;(add-to-list 'load-path "~/.emacs.d/el-get/color-theme")
;;(load-file "~/.emacs.d/el-get/color-theme/color-theme.el")
;;(require 'color-theme)
;;(color-theme-initialize)

;;(add-to-list 'load-path "~/.emacs.d/el-get/color-theme")
(require 'color-theme)
(color-theme-initialize)
(add-to-list 'load-path "/opt/emacs/helpers/color-theme-twilight")
(require 'color-theme-twilight)
(color-theme-twilight)
;;; (set-default-font "Apple Monaco-9")
;; (set-fontset-font (frame-parameter nil 'font)
;;             'han '("Microsoft YaHei" . "unicode-bmp")) 
;; (set-fontset-font (frame-parameter nil 'font)
;;             'cjk-misc '("SimSun" . "unicode-bmp"))
;; (set-fontset-font (frame-parameter nil 'font)
;;             'kana '("SimSun" . "unicode-bmp")) 
;; (set-fontset-font (frame-parameter nil 'font)
;;             'symbol '("SimSun" . "unicode-bmp"))
;; 自动检测编码 code.google.com
